user:
  name: Rudolf Braun-Lee
  email: braun.ru@outlook.de
  github_username: braunrudolf

brew_bin: "/opt/homebrew/bin/brew"

setup_brew:
  formulae:
    - nvim
    - stow
    - npm
    - tree-sitter-cli
    - ripgrep
    - make
    - gcc
    - fd
    - starship

  cask:
    - nikitabobko/tap/aerospace
    - iterm2
    - betterdisplay
    - brave-browser
    - makemkv
    - utm
    - discord
    - whatsapp
    - obsidian

macos_settings:
  dock:
    autohide: true
    tilesize: 48
    show_recents: false
  finder:
    show_all_extensions: true
    default_view_style: "clmv" # Column view
    show_path_bar: true

dotfiles:
  repo: "https://github.com/BraunRudolf/.dotfiles.git"
  dest: "{{ ansible_facts['env']['HOME'] }}/.dotfiles"
  subdirs:
    - common
    - macos
  config_destination: "{{ ansible_facts['env']['HOME'] }}/.config"
features:
  install_oh_my_zsh: true
  configure_git: true
